services:
  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: rvcc_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
#    entrypoint: ["entrypoint.dev.sh"]
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
      - bundle_cache:${rvm_path}/gems/ruby-4.0.1
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/rvcc_development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_LOG_TO_STDOUT: "true"
#      VITE_RUBY_HOST: vite
    depends_on:
      db:
        condition: service_healthy
#      vite:
#        condition: service_started
    stdin_open: true
    tty: true

#  vite:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    entrypoint: ["entrypoint.vite.sh"]
#    command: ./bin/vite dev
#    volumes:
#      - .:/rails
#      - bundle_cache:${rvm_path}/gems/ruby-4.0.1
#      - node_modules:/rails/node_modules
#    ports:
#      - "3036:3036"
#    environment:
#      RAILS_ENV: development
#      NODE_ENV: development
#    stdin_open: true
#    tty: true
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:3036/vite-dev/"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 40s

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
#    entrypoint: ["entrypoint.dev.sh"]
    command: tail -f /dev/null
    volumes:
      - .:/rails
      - bundle_cache:${rvm_path}/gems/ruby-4.0.1
      - node_modules:/rails/node_modules
    ports:
      - "9222:9222"
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@db:5432/rvcc_test
      RAILS_LOG_TO_STDOUT: "true"
#      VITE_RUBY_HOST: vite
    depends_on:
      db:
        condition: service_healthy
#      vite:
#        condition: service_started
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache:
  node_modules: